version: '3'

networks:
  asist_net:
   external: true    
    
services:
  speech_analyzer_agent:
    image: speech_analyzer_agent:latest
    container_name: speech_analyzer_agent
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/google_application_credentials.json/google_application_credentials.json
    volumes:
      - ./google_application_credentials.json:/google_application_credentials.json
    networks:
      asist_net:
        aliases:
          - speech_analyzer_agent
    entrypoint: ./speechAnalyzer --mode websocket

