version: '3'

networks:
  asist_net:
   external: true    
    
services:
  speech_analyzer_agent:
    image: speech_analyzer_agent:latest
    container_name: speech_analyzer_agent
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/google_application_credentials.json/google_application_credentials.json
    volumes:
      - ./google_application_credentials.json:/google_application_credentials.json
    networks:
      asist_net:
        aliases:
          - speech_analyzer_agent
    entrypoint: ./speechAnalyzer --mode websocket --disable_opensmile false
  vosk:
    image: alphacep/kaldi-en:latest
    container_name: vosk
    ports:
      - 2700:2700
    networks:
      asist_net:
        aliases:
          - vosk
  mmc:
    image: mmc:1.0.0
    container_name: mmc
    networks:
      asist_net:
        aliases:
          - mmc
    entrypoint: uvicorn mmc_server:app --host 0.0.0.0 --port 8001

  heartbeat:
    image: heartbeat:latest
    container_name: heartbeat
    volumes:
      - ./config.json:/heartbeat/config.json
    networks:
      asist_net:
        aliases:
          - heartbeat
    entrypoint: ["python3", "heartbeat.py"]
