#!/usr/bin/env bash

# Install OpenSMILE from source.

set -euo

git clone https://github.com/audeering/opensmile.git
pushd opensmile
    mkdir build
    cd build
    cmake ..
    make -j
    make -j install
popd
